//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GFBA.Exception {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceErrorMessages() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GFBA.Exception.ResourceErrorMessages", typeof(ResourceErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cargo do usuário inválido..
        /// </summary>
        public static string CARGO_INVALIDO {
            get {
                return ResourceManager.GetString("CARGO_INVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O contato do responsável não pode ter mais de 45 caracteres..
        /// </summary>
        public static string CONTATO_RESPONSAVEL_MAXIMO_QUARENTA_CINCO_CARACTERES {
            get {
                return ResourceManager.GetString("CONTATO_RESPONSAVEL_MAXIMO_QUARENTA_CINCO_CARACTERES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O contato do responsável deve ter no mínimo dez caracteres..
        /// </summary>
        public static string CONTATO_RESPONSAVEL_MINIMO_DEZ_CARACTERES {
            get {
                return ResourceManager.GetString("CONTATO_RESPONSAVEL_MINIMO_DEZ_CARACTERES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Contato do responsável é obrigatório..
        /// </summary>
        public static string CONTATO_RESPONSAVEL_OBRIGATORIO {
            get {
                return ResourceManager.GetString("CONTATO_RESPONSAVEL_OBRIGATORIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A data de abertura da ficha de Busca Ativa não pode ser do futuro..
        /// </summary>
        public static string DATA_ABERTURA_INVALIDA {
            get {
                return ResourceManager.GetString("DATA_ABERTURA_INVALIDA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A data da ação da Busca Ativa não pode ser do futuro..
        /// </summary>
        public static string DATA_ACAO_BA_INVALIDA {
            get {
                return ResourceManager.GetString("DATA_ACAO_BA_INVALIDA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Data de nascimento inválida..
        /// </summary>
        public static string DATA_NASCIMENTO_INVALIDA {
            get {
                return ResourceManager.GetString("DATA_NASCIMENTO_INVALIDA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a E-mail inválido..
        /// </summary>
        public static string EMAIL_INVALIDO {
            get {
                return ResourceManager.GetString("EMAIL_INVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O e-mail não pode ter mais de cem caracteres..
        /// </summary>
        public static string EMAIL_MAIOR_CEM_CARACTERES {
            get {
                return ResourceManager.GetString("EMAIL_MAIOR_CEM_CARACTERES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O e-mail é obrigatório..
        /// </summary>
        public static string EMAIL_OBRIGATORIO {
            get {
                return ResourceManager.GetString("EMAIL_OBRIGATORIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Erro desconhecido..
        /// </summary>
        public static string ERRO_DESCONHECIDO {
            get {
                return ResourceManager.GetString("ERRO_DESCONHECIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O número da matrícula deve ter no mínimo dez caracteres..
        /// </summary>
        public static string MATRICULA_DEZ_CARACTERES {
            get {
                return ResourceManager.GetString("MATRICULA_DEZ_CARACTERES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O número da matrícula não pode ter mais de doze caracteres..
        /// </summary>
        public static string MATRICULA_MAIOR_DOZE_CARACTERES {
            get {
                return ResourceManager.GetString("MATRICULA_MAIOR_DOZE_CARACTERES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O número de matrícula é obrigatório..
        /// </summary>
        public static string MATRICULA_OBRIGATORIA {
            get {
                return ResourceManager.GetString("MATRICULA_OBRIGATORIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Motivo inválido..
        /// </summary>
        public static string MOTIVO_INVALIDO {
            get {
                return ResourceManager.GetString("MOTIVO_INVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O nome deve conter no mínimo 2 caracteres..
        /// </summary>
        public static string NOME_DOIS_CARACTERES {
            get {
                return ResourceManager.GetString("NOME_DOIS_CARACTERES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O nome não pode ter mais de 100 caracteres..
        /// </summary>
        public static string NOME_MAIOR_CEM_CARACTERES {
            get {
                return ResourceManager.GetString("NOME_MAIOR_CEM_CARACTERES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O nome é obrigatório..
        /// </summary>
        public static string NOME_OBRIGATORIO {
            get {
                return ResourceManager.GetString("NOME_OBRIGATORIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O campo Observações não pode conter mais de 500 caracteres..
        /// </summary>
        public static string OBSERVACOES_MAXIMO_QUINHENTOS_CARACTERES {
            get {
                return ResourceManager.GetString("OBSERVACOES_MAXIMO_QUINHENTOS_CARACTERES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Sua senha deve ter, no mínimo, 8 caracteres, contendo uma letra maiúscula, uma minúscula, um número e um caractere especial (ex: ., !, ?, *, #)..
        /// </summary>
        public static string SENHA_INVALIDA {
            get {
                return ResourceManager.GetString("SENHA_INVALIDA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Status inválido..
        /// </summary>
        public static string STATUS_INVALIDO {
            get {
                return ResourceManager.GetString("STATUS_INVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Tipo de ação de Busca Ativa inválido..
        /// </summary>
        public static string TIPO_ACAO_BA_INVALIDO {
            get {
                return ResourceManager.GetString("TIPO_ACAO_BA_INVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Turma inválida..
        /// </summary>
        public static string TURMA_INVALIDA {
            get {
                return ResourceManager.GetString("TURMA_INVALIDA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Turma é obrigatória..
        /// </summary>
        public static string TURMA_OBRIGATORIA {
            get {
                return ResourceManager.GetString("TURMA_OBRIGATORIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Turno inválido..
        /// </summary>
        public static string TURNO_INVALIDO {
            get {
                return ResourceManager.GetString("TURNO_INVALIDO", resourceCulture);
            }
        }
    }
}
