<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="12.1.1" />
    <PackageReference Include="Mapster" Version="10.0.12" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="9.0.19" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Shared\GFBA.Communication\GFBA.Communication.csproj" />
    <ProjectReference Include="..\..\Shared\GFBA.Exception\GFBA.Exception.csproj" />
    <ProjectReference Include="..\GFBA.Domain\GFBA.Domain.csproj" />
  </ItemGroup>

</Project>
